#!/bin/bash

Xlim=20
scale=10
plane=xy
flip=0
RotateX=0
RotateY=0
RotateZ=0
NoLabels=0
Colors=0
NoH=0
space="   "

# Reset
NC='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
LightGrey='\033[0;37m'        # LightGrey

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White
On_Grey='\033[2;47m'   # Grey

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White
On_IGrey='\033[2;107m'   # Grey


PrintHelp (){
	echo "PrintMolecule. -h for help (this message)"
	echo ""
	echo "Usage: PrintMolecule [Filename] [-s scale (optional)] [-p plane (optional)] [-r rotation (optional)] [ -v (optional) ] [ -H (optional) ] [ -L (optional) ]"
	printf "\tFilename: either a gaussian output file or a xyz file\n"
	printf "\t-s [scale]: an integer. Default = 10. Ideal range: 3-20\n"
	printf "\t-p [plane]: projection plane: xy, yz or xz. Default: xy.\n"
	printf "\t-r / --rz [rotation]: angle rotation along off-screen (z-)axis in degrees, anti-clockwise. Range: -180-180. Default: 0.\n"
	printf "\t--ry [rotation]: angle rotation along on-screen vertical (y-)axis in degrees, anti-clockwise. Range: -180-180. Default: 0.\n"
	printf "\t--rx [rotation]: angle rotation along on-screen horizontal (x-)axis in degrees, anti-clockwise. Range: -180-180. Default: 0.\n"
	printf "\t-v: vertical flip (rotate 180 degrees along on-screen y-axis). Vertical flip is always performed after rotation.\n"
	printf "\t-H: remove hydrogens\n"
	printf "\t-L: remove labels\n"
	printf "\t-c: color some of the atoms. Default is shades of grey based on off-screen depth. Depth-based color is incompatible with -c\n"
	printf "\n"
	printf "Info: rotations are always performed in this order: z, y, x.\n\n"
	exit
}

WriteAtomMatrix (){
	
	if [ "$(grep "Symmetry turned off" $File)" ]; then
	        line=$(awk '/Input orientation:/{ print NR+5}' $File | tail -n1)
	else
	        line=$(awk '/Standard orientation:/{ print NR+5}' $File | tail -n1) 
	fi

	if [ -z $line ]; then
		echo "Couldn't get matrix from file"
		exit
	fi

	atoms=$(awk '/NAtoms=/{print $2}' $File | head -1)

        awk 'FNR=='$line',FNR=='$line+$atoms-1'{print $2}' OFS='\t' $File  > atoms.oti.tmp
        
        if [ $(awk 'FNR=='$line-5',FNR=='$line'{print $0}' OFS='\t' $File | grep "Type" | awk '{print $1}') ]; then
                awk 'FNR=='$line',FNR=='$line+$atoms-1'{print $1,$4,$5,$6}' OFS='\t' $File > matrix.oti.tmp
        else    
                awk 'FNR=='$line',FNR=='$line+$atoms-1'{print $1,$3,$4,$5}' OFS='\t' $File > matrix.oti.tmp
        fi
        
        sed -i 's/31/Ga/g' atoms.oti.tmp
        sed -i 's/32/Ge/g' atoms.oti.tmp
        sed -i 's/33/As/g' atoms.oti.tmp
        sed -i 's/34/Se/g' atoms.oti.tmp
        sed -i 's/35/Br/g' atoms.oti.tmp
        sed -i 's/10/Ne/g' atoms.oti.tmp
        sed -i 's/11/Na/g' atoms.oti.tmp
        sed -i 's/12/Mg/g' atoms.oti.tmp
        sed -i 's/13/Al/g' atoms.oti.tmp
        sed -i 's/14/Si/g' atoms.oti.tmp
        sed -i 's/15/P/g' atoms.oti.tmp
        sed -i 's/16/S/g' atoms.oti.tmp
        sed -i 's/17/Cl/g' atoms.oti.tmp
        sed -i 's/18/Ar/g' atoms.oti.tmp
        sed -i 's/1/H/g' atoms.oti.tmp
        sed -i 's/2/He/g' atoms.oti.tmp
        sed -i 's/3/Li/g' atoms.oti.tmp
        sed -i 's/4/Be/g' atoms.oti.tmp
        sed -i 's/5/B/g' atoms.oti.tmp
        sed -i 's/6/C/g' atoms.oti.tmp
        sed -i 's/7/N/g' atoms.oti.tmp
        sed -i 's/8/O/g' atoms.oti.tmp
        sed -i 's/9/F/g' atoms.oti.tmp
        
	sed -i '1,9s/^/0/' matrix.oti.tmp
        paste atoms.oti.tmp matrix.oti.tmp | awk '{printf " %-3s %5s %15s %15s %15s\n", $1, $2, $3, $4, $5}' > xyzMatrix.tmp
        rm atoms.oti.tmp matrix.oti.tmp
}


if [ -z $1 ]; then
	echo "Give me a file. Should be an xyz, gaussian output file (.log) or whatever"
	PrintHelp
elif [ $1 == "-h" ]; then
	PrintHelp
fi


for i in $(seq 1 $#); do
        CurrStr=$(echo "$@" | awk '{print $'$i'}')
        FollowingStr=$(echo "$@" | awk '{print $('$i'+1)}')

        case $CurrStr in
		*.xyz)
			FileType=xyz
			File=$1 ;;
		*.log)
			if [ "$(grep "Gaussian, Inc.  All Rights Reserved" $1)" ]; then
                		FileType=GaussianLog
        		else
                		echo "Don't know what to do with this"
                		exit
        		fi
			File=$1 ;;
		-s)	
			if [ $FollowingStr -ge 1 ]; then
				scale=$FollowingStr
			else
				echo "Scaling factor must be grater than 0"
				exit
			fi ;;
		-p)	
			plane=$FollowingStr
			if [ $plane != "xy" ] && [ $plane != "yz" ] && [ $plane != "xz" ]; then
				echo "Error: planes can be xy, yz and xz"
				exit
			fi;;
		-r | --rz)
			rotationZ=$FollowingStr
			RotateZ=1
			if [ -z $(echo $rotationZ | grep -e "^[0-9]" -e "^-[0-9]") ]; then
				echo "Error: rotation angle must be an integer"
				exit
			elif [ $rotationZ -eq 0 ]; then
				RotateZ=0
			else
				radZ=$(awk 'BEGIN{printf "%.3f\n", 3.1416 * '$rotationZ' / 180 }')
				cosAZ=$(awk 'BEGIN{printf "%.3f\n", cos('$radZ')}')
				sinAZ=$(awk 'BEGIN{printf "%.3f\n", sin('$radZ')}')
			fi;;
		--ry)
                        rotationY=$FollowingStr
                        RotateY=1
                        if [ -z $(echo $rotationY | grep -e "^[0-9]" -e "^-[0-9]") ]; then
                                echo "Error: rotation angle must be an integer"
                                exit
                        elif [ $rotationY -eq 0 ]; then
                                RotateY=0
                        else
                                radY=$(awk 'BEGIN{printf "%.3f\n", 3.1416 * '$rotationY' / 180 }')
                                cosAY=$(awk 'BEGIN{printf "%.3f\n", cos('$radY')}')
                                sinAY=$(awk 'BEGIN{printf "%.3f\n", sin('$radY')}')
                        fi;;
		--rx)
                        rotationX=$FollowingStr
                        RotateX=1
                        if [ -z $(echo $rotationX | grep -e "^[0-9]" -e "^-[0-9]") ]; then
                                echo "Error: rotation angle must be an integer"
                                exit
                        elif [ $rotationX -eq 0 ]; then
                                RotateX=0
                        else
                                radX=$(awk 'BEGIN{printf "%.3f\n", 3.1416 * '$rotationX' / 180 }')
                                cosAX=$(awk 'BEGIN{printf "%.3f\n", cos('$radX')}')
                                sinAX=$(awk 'BEGIN{printf "%.3f\n", sin('$radX')}')
                        fi;;

		-v)	flip=1;;
		-L)	NoLabels=1;;
		-H)	NoH=1;;
		-c)	Colors=1;;

	esac
done


case $FileType in

	xyz)
		NR=$(awk 'END{print NR}' $File)
		if [ -z "$(awk 'FNR=='$NR'{print $1}' $File)" ]; then
			NR=$((NR-1))
		fi
		sed -n '3,'$NR'p' $File > xyzMatrix.tmp
		NAtoms=$((NR-2))
		for num in $(seq 1 $NAtoms); do
			echo "$num" >> labels.tmp
		done
		sed -i '1,9s/^/0/' labels.tmp
		awk '{print $1}' xyzMatrix.tmp > atoms.tmp
		awk '{print $2,$3,$4}' xyzMatrix.tmp > xyzvalues.tmp
		paste atoms.tmp labels.tmp xyzvalues.tmp | awk '{printf " %-3s %5s %15s %15s %15s\n", $1, $2, $3, $4, $5}' > xyzMatrix.tmp
		rm labels.tmp atoms.tmp xyzvalues.tmp
		;;
	
	GaussianLog)
		WriteAtomMatrix		
		NAtoms=$atoms
		;;

esac


if [ $plane == "xy" ]; then
	awk '{print $3,$4,$5}' xyzMatrix.tmp > XYZvalues.tmp
elif [ $plane == "xz" ]; then
	awk '{print $3,$5,$4}' xyzMatrix.tmp > XYZvalues.tmp
elif [ $plane == "yz" ]; then
	awk '{print $4,$5,$3}' xyzMatrix.tmp > XYZvalues.tmp
fi



if [ $RotateZ -eq 1 ]; then
	for num in $(seq 1 $NAtoms); do		#rotate along off-screen axis (Z)
                X_old=$(awk 'FNR=='$num'{print $1}' XYZvalues.tmp)
                Y_old=$(awk 'FNR=='$num'{print $2}' XYZvalues.tmp)
		Z_old=$(awk 'FNR=='$num'{print $3}' XYZvalues.tmp)
                X_new=$(awk 'BEGIN{printf "%.4f\n", '$X_old' * '$cosAZ' - '$Y_old' * '$sinAZ' }')
                Y_new=$(awk 'BEGIN{printf "%.4f\n", '$X_old' * '$sinAZ' + '$Y_old' * '$cosAZ' }')
                printf -- "$X_new\t$Y_new\t$Z_old\n" >> new_XYZvalues.tmp
        done
        mv new_XYZvalues.tmp XYZvalues.tmp
fi


if [ $RotateY -eq 1 ]; then
        for num in $(seq 1 $NAtoms); do         #rotate along off-screen axis (Z)
                X_old=$(awk 'FNR=='$num'{print $1}' XYZvalues.tmp)
                Y_old=$(awk 'FNR=='$num'{print $2}' XYZvalues.tmp)
                Z_old=$(awk 'FNR=='$num'{print $3}' XYZvalues.tmp)
                X_new=$(awk 'BEGIN{printf "%.4f\n", '$X_old' * '$cosAY' - '$Z_old' * '$sinAY' }')
                Z_new=$(awk 'BEGIN{printf "%.4f\n", '$X_old' * '$sinAY' + '$Z_old' * '$cosAY' }')
                printf -- "$X_new\t$Y_old\t$Z_new\n" >> new_XYZvalues.tmp
        done
        mv new_XYZvalues.tmp XYZvalues.tmp
fi


if [ $RotateX -eq 1 ]; then
        for num in $(seq 1 $NAtoms); do         #rotate along off-screen axis (Z)
                X_old=$(awk 'FNR=='$num'{print $1}' XYZvalues.tmp)
                Y_old=$(awk 'FNR=='$num'{print $2}' XYZvalues.tmp)
                Z_old=$(awk 'FNR=='$num'{print $3}' XYZvalues.tmp)
                Y_new=$(awk 'BEGIN{printf "%.4f\n", '$Y_old' * '$cosAX' - '$Z_old' * '$sinAX' }')
                Z_new=$(awk 'BEGIN{printf "%.4f\n", '$Y_old' * '$sinAX' + '$Z_old' * '$cosAX' }')
                printf -- "$X_old\t$Y_new\t$Z_new\n" >> new_XYZvalues.tmp
        done
        mv new_XYZvalues.tmp XYZvalues.tmp
fi


if [ $flip -eq 1 ]; then
	sort -k1n XYZvalues.tmp > sorted_XYZvalues.tmp      #sort matrix based on X values (ascending)

	minX=$(awk 'FNR==1{print $1}' sorted_XYZvalues.tmp)
	maxX=$(awk 'END{print $1}' sorted_XYZvalues.tmp)
	midX=$(awk 'BEGIN{printf "%.6f\n", '$minX' + ( ( '$maxX' - '$minX' ) / 2 )}')

	rm sorted_XYZvalues.tmp

	for num in $(seq 1 $NAtoms); do		#rotate along on-screen y axis (Y)
		X_old=$(awk 'FNR=='$num'{print $1}' XYZvalues.tmp)
                X_new=$(awk 'BEGIN{printf "%.4f\n",  2*'$midX' - '$X_old' }')
		Y_old=$(awk 'FNR=='$num'{print $2}' XYZvalues.tmp)
		Z_new=$(awk 'FNR=='$num'{print -$3}' XYZvalues.tmp)
		printf -- "$X_new\t$Y_old\t$Z_new\n" >> new_XYZvalues.tmp
	done
	mv new_XYZvalues.tmp XYZvalues.tmp
fi



ScaleFact=$(awk 'BEGIN{printf "%.2f\n", '$scale' / 5 }')

awk '{print $1$2}' xyzMatrix.tmp > symbols.tmp
awk '{printf "%.0f\n", $1 * '$ScaleFact'}' XYZvalues.tmp > Xvalues.tmp
awk '{printf "%.0f\n", $2 * '$ScaleFact'}' XYZvalues.tmp > Yvalues.tmp

minZ=$(sort -k3n XYZvalues.tmp | awk '{printf "%.2f\n", $3}' | head -1)
maxZ=$(sort -k3n XYZvalues.tmp | awk '{printf "%.2f\n", $3}' | tail -1)

depth=$(awk 'BEGIN{printf "%.2f\n", '$maxZ' - '$minZ' }')	#Z-axis depth

if (( $(echo "$depth <= 0.1" |bc -l) )); then
	awk '{printf "%.0f\n", 5}' XYZvalues.tmp > Zvalues.tmp
else
	awk '{printf "%.0f\n", 10 * (( $3 - '$minZ' ) / '$depth') }' XYZvalues.tmp > Zvalues.tmp
fi

paste symbols.tmp Xvalues.tmp Yvalues.tmp Zvalues.tmp > scaled_XYZMatrix.tmp

rm symbols.tmp Xvalues.tmp Yvalues.tmp Zvalues.tmp XYZvalues.tmp xyzMatrix.tmp

minX=$(sort -k2n scaled_XYZMatrix.tmp | awk '{print $2}' | head -1)
maxX=$(sort -k2n scaled_XYZMatrix.tmp | awk '{print $2}' | tail -1)
width=$(echo $" $(echo ${maxX#-}) + $(echo ${minX#-}) " | bc)

sort -k3rn -k2n scaled_XYZMatrix.tmp > sorted_XYZMatrix.tmp      #sort matrix based on y values (descending) and the x values (ascending)

rm scaled_XYZMatrix.tmp

col=$(stty size | cut -d" " -f2)
col=$((col/3))

minX=$(( minX - (col- width)/2 ))

if [ $width -ge $col ]; then
	echo "Error: too large scaling factor"
	exit
fi

matfile=sorted_XYZMatrix.tmp

if [ $NoH -eq 1 ]; then
	sed -i '/^H/d' $matfile
	NAtoms=$(awk 'END{print NR}' $matfile)
fi


for i in $(seq 1 $NAtoms); do
	Symbol[$i]=$(awk 'FNR=='$i'{print $1}' $matfile)
	X_values[$i]=$(awk 'FNR=='$i'{print $2}' $matfile)
	Y_values[$i]=$(awk 'FNR=='$i'{print $3}' $matfile)
	Z_values[$i]=$(awk 'FNR=='$i'{print $4}' $matfile)
	if [ $Colors -eq 1 ]; then 
		case ${Symbol[$i]} in
			N[0-9]*) Color[$i]=$On_IBlue;;
			H[0-9]*) Color[$i]="$Black"$On_IGrey;;
			C[0-9]*) Color[$i]="$White"$On_IBlack;;
			O[0-9]*) Color[$i]=$On_Red;;
			S[0-9]*) Color[$i]=$On_Yellow;;
		esac
	else
		if [ ${Z_values[$i]} -lt 2 ]; then
			Color[$i]=$IBlack
		elif [ ${Z_values[$i]} -lt 4 ]; then
			Color[$i]=${On_IBlack}${LightGrey}
		elif [ ${Z_values[$i]} -ge 8 ]; then
			Color[$i]=$BIWhite
		else
			Color[$i]=$NC
		fi
	fi
done

if [ $NoLabels -eq 1 ]; then
	space="  "
	for i in $(seq 1 $NAtoms); do
		Symbol[$i]=$(echo "${Symbol[$i]}" | tr -d '0123456789')
	done
fi

maxY=${Y_values[1]}
minY=${Y_values[$NAtoms]}


echo "Molecule structure:"

currline=$((maxY+3))
currspace=0


for n in $(seq 1 $NAtoms); do
	currY=${Y_values[$n]}	
	currX=${X_values[$n]}

	linediff=$((currline - currY))
	
	if [ $linediff -ne 0 ]; then
		currspace=0
	fi
	
	spacediff=$((currX - minX - currspace))
	

	for lines in $(seq 1 $linediff); do
		echo ""
	done
	for spaces in $(seq 2 $spacediff); do
		printf "$space"
	done
	printf "${Color[$n]}${Symbol[$n]}${NC}"

	currspace=$((currX - minX))
	currline=$currY

done


linediff=3
#linediff=$((currY + 10))

for lines in $(seq 1 $linediff); do
                echo ""
done


printf "\n"
echo "-----------------------------------------------------------------------"

rm sorted_XYZMatrix.tmp 
